BEGIN;

DROP TABLE IF EXISTS master_counters CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS products CASCADE;

DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS order_products CASCADE;

COMMIT;